//Operadores ARITMÉTICOS
/* 
SOMA +
CONCATENAR +
SUBTRAÇÃO -
PÔTENCIA ** OU ^
DIVISÃO /
RESTO %


*/
//OPERADORES DE ATRIBUIÇÃO
/* 
ATRIBUIÇÃO =
ATRIBUI E SOMA +=
ATRIBUI E SUBTRAI -=
ATRIBUI E MULTIPLICA *=
ATRIBUI E DIVIDI/=
ATRIBUI E ELEVA A POTÊNCIA**=
*/

//OPERADORES RELACIONAIS

/* 
IGUALDADE == (* NÃO CONSIDERPA TIPO DE DADO)
IGUALDADE RESTRITA === ("COMPARÁ TAMBÉM O TIPO DE DADO")
MAIOR DO QUE >
MAIOR E IGUAL DO QUE >=
MENOR DO QUE <
MENOR E IGUAL DO QUE <=
DIFERENTE !=
*/

//OPERADOR DE EXPRESSÃO DE LOGICA
/*
AND --> &&
OU  --> ||
NOT --> !

 */